import numpy as np
import pandas as pd

# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

# Set URL for the Wikipedia page
URL = "https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"

# Extract all tables from webpage using Pandas
tables = pd.read_html(URL)
df = tables[3] # Select the third table from the list of tables

# Replace the column headers with column numbers (0, 1, 2, ...)
df.columns = range(df.shape[1])

# Retain columns with index 0 and 2 (name of country and value of GDP quoted by IMF)
df = df[[0, 2]]

# Retain the Rows with index 1 to 10, indicating the top 10 economies of the world.
df = df.iloc[1:11,:]

# Assign column names as "Country" and "GDP (Million USD)"
df.columns = ["Country", "GDP (Million USD)"]

# Change the data type of the 'GDP (Million USD)' column to integer. Use astype() method.
df["GDP (Million USD)"] = df["GDP (Million USD)"].astype(int)

# Convert the GDP value in Million USD to Billion USD
df[["GDP (Million USD)"]] = df[["GDP (Million USD)"]] / 1000 # Convert to Billion USD
df[["GDP (Million USD)"]] = np.round(df[["GDP (Million USD)"]], 2) # Round to 2 decimal places
df.rename(columns = {'GDP (Million USD)' : 'GDP (Billion USD)'}, inplace=True)

# Save the DataFrame to a CSV file (without index as first column)
df.to_csv('Largest_economies.csv', index=False)